#!/usr/bin/env python3

import csv
import json

# BUG: does not deal nicely with " characters

memes = []
with open('content.csv', newline='') as csvfile:
    spamreader = csv.reader(csvfile, delimiter=',', quotechar='"')
    for row in spamreader:
        r = [x.replace('\n', '<br/>') for x in row]
        # all elements are filled in and ready is marked
        if len(r) > 7 and all(v for v in r[:7]) and (r[6] == 'yes' or r[6] == 'y'):
            memes.append((r[0], r[1] + '.jpg', r[2], r[3], r[4], r[5]))

with open('static/memes.js', 'w') as outfile:
    outfile.write('''// generated by loadcontent.py, do not modify by hand
var hashes = [];
var excuse = [];
var meme = [];
var alt = [];
var footnotes = [];
var info = [];

// static content for the main page
hashes.push("");
meme.push("eagle.jpg");
alt.push("What is your excuse not to vote?");
excuse.push("");
footnotes.push("");
info.push("");

// load everything else''')
    for m in memes:
        outfile.write('''
hashes.push("{}");
meme.push("{}");
alt.push("{}");
excuse.push("{}");
footnotes.push("{}");
info.push("{}");'''.format(*m))
    
    outfile.close()
